service: ${file(./config.yml):service_name}

provider:
  name: aws
  runtime: nodejs6.10
  stage: stage
  region: us-east-1

package:
  artifact: dist.zip

functions:
  ssr:
    handler: handler.ssr
    events:
      - http:
          method: get
          path: ${self:service}
      - http:
          method: any
          path: "${self:service}/{proxy+}"

  sendSheet:
    handler: handler.sendSheet
    events:
      - http:
          method: post
          path: "sendSheet"
          cors: true

  getUsers:
    handler: handler.getUsers
    events:
      - http:
          method: get
          path: "getUsers"
          cors: true

  getUserCount:
    handler: handler.getUserCount
    events:
      - http:
          method: get
          path: "getUserCount"
          cors: true

resources:
  Resources: ${file(cloudformation.json)}
